var random_nouns = [
  "cat",
  "dog",
  "fish",
  "bird",
  "mouse",
  "hamster",
  "rabbit",
  "turtle",
  "snake",
  "lizard",
  "monkey",
  "elephant",
  "giraffe",
  "zebra",
  "lion",
  "tiger",
  "bear",
  "wolf",
  "fox",
  "deer",
  "horse",
  "cow",
  "pig",
  "sheep",
  "goat",
  "chicken",
  "duck",
  "turkey",
  "rooster",
  "dinosaur",
  "dragon",
  "unicorn",
  "panda",
  "koala",
  "kangaroo",
  "squirrel",
  "raccoon",
  "beaver",
  "octopus",
  "jellyfish",
  "starfish",
  "seahorse",
  "crab",
  "lobster",
  "shark",
  "jellyfish",
  "octopus",
  "squid",
  "clownfish",
  "dolphin",
  "whale",
  "seal",
  "otter",
  "penguin",
  "flamingo",
  "eagle",
  "owl",
  "parrot",
  "peacock",
  "swan",
  "desk",
  "chair",
  "computer",
  "book",
  "phone",
  "keyboard",
  "lamp",
  "guitar",
  "table",
  "bottle",
  "pen",
  "paper",
  "monitor",
  "clock",
  "calendar",
  "plant",
  "headphones",
  "notebook",
  "backpack",
  "shoes",
  "glasses",
  "watch",
  "wallet",
  "bag",
  "camera",
  "microphone",
  "towel",
  "umbrella",
  "scarf",
  "hat",
  "gloves",
  "socks",
  "piano",
  "couch",
  "TV",
  "remote",
  "speakers",
  "mirror",
  "brush",
  "toothpaste",
  "soap",
  "shampoo",
  "conditioner",
  "perfume",
  "lotion",
  "comb",
  "scissors",
  "tissue",
  "key",
  "ring",
  "bracelet",
  "necklace",
  "earrings",
  "belt",
  "tie",
  "wallet",
  "coin",
  "stamp",
  "sedan",
  "SUV",
  "minivan",
  "supercar",
  "wagon",
  "limousine",
  "luxury",
  "racing",
  "van",
  "caravan",
  "buggy",
  "motorhome",
  "tow truck",
  "dump truck",
  "fire truck",
  "garbage truck",
  "ice cream truck",
  "semi-truck",
  "tractor",
  "bike",
  "snowmobile",
  "monster truck",
  "pickup truck",
  "happiness",
  "sadness",
  "angriness",
  "excitedness",
  "nervousness",
  "overwhelmingness",
  "contentness",
  "gratefulness",
  "hopefulness",
  "peacefulness",
  "love story",
  "loneliness",
  "frustration",
  "silliness",
  "confidence",
  "boredom",
  "proudness",
  "fearfulness",
  "guiltiness",
  "curiosity",
  "a surprise",
  "annoyance",
  "pensiveness",
  "melancholy",
  "nostalgia",
  "thoughtfulness",
  "restlessness",
  "calmness",
  "apprehensiveness",
  "pessimistic people",
  "optimistic people",
  "determination",
  "hopelessness",
  "grumpiness",
  "disappointedness",
  "thrillness",
  "enviousness",
  "depression",
  "exhaustion",
  "indifference",
  "resentfulness",
  "fascination",
  "eagerness",
  "confusion",
  "crankiness",
  "broken heart",
  "disenchanting",
  "disorienting",
  "tank",
  "fighter jet",
  "helicopter",
  "submarine",
  "aircraft carrier",
  "bomber",
  "destroyer",
  "missile launcher",
  "assault rifle",
  "sniper rifle",
  "grenade launcher",
  "fighter plane",
  "battleship",
  "stealth bomber",
  "artillery cannon",
  "rocket launcher",
  "anti-aircraft gun",
  "machine gun",
  "naval mine",
  "mortar",
  "flamethrower",
  "hand grenade",
  "landmine",
  "armored vehicle",
  "missile",
  "drone",
  "nuclear submarine",
  "cruise missile",
  "tactical nuke",
  "bayonet",
  "anti-tank missile",
  "torpedo",
  "howitzer",
  "SAM launcher",
  "grenade",
  "landmine",
  "cluster bomb",
  "chemical weapon",
  "biological weapon",
  "EMP weapon",
  "tactical missile",
  "smart bomb",
  "daisy cutter",
  "thermonuclear weapon",
  "battle tank",
  "fighter submarine",
  "attack helicopter",
  "stealth aircraft",
  "guided missile",
  "tactical drone",
  "stealth fighter",
  "heat-seeking missile",
  "anti-ship missile",
  "surface-to-air missile",
  "intercontinental ballistic missile",
  "tank destroyer",
  "combat helicopter",
  "reconnaissance aircraft",
  "strategic bomber",
  "mobile rocket launcher",
  "strategic missile",
  "anti-tank weapon",
  "combat drone",
  "torpedo boat",
  "anti-personnel mine",
  "cryogenic weapon",
  "railgun",
  "sonic weapon",
  "laser weapon",
  "railgun",
  "plasma weapon",
  "particle beam weapon",
  "gravity weapon",
  "ion cannon",
  "tesla weapon",
  "quantum weapon",
  "lightning weapon",
  "freeze ray",
  "energy weapon",
  "microwave weapon",
  "pulsar weapon",
  "neutron weapon",
  "acid weapon",
  "bioweapon",
  "nanoweapon",
  "psychotronic weapon",
  "singularity weapon",
  "pulse weapon",
  "disintegrator",
  "vortex weapon",
  "doomsday weapon",
  "death ray",
  "doomsday device",
  "mountains",
  "caves",
  "forests",
  "valleys",
  "rivers",
  "waterfalls",
  "islands",
  "deserts",
  "jungles",
  "volcanoes",
  "dragons",
  "pirates",
  "treasure",
  "quests",
  "mystical creatures",
  "magic",
  "evil sorcerers",
  "knights",
  "princesses",
  "castles",
  "secret passages",
  "buried treasure",
  "shipwrecks",
  "mysterious maps",
  "enchanted forests",
  "hidden temples",
  "adventure",
  "exploration",
  "mystery",
  "secrets",
  "intrigue",
  "danger",
  "heroes",
  "villains",
  "fortune",
  "fame",
  "power",
  "divine intervention",
  "fated encounters",
  "unfathomable odds",
  "epic battles",
  "lost civilizations",
  "ancient relics",
  "mythical beasts",
  "legendary weapons",
  "mystical artifacts",
  "fateful prophecies",
  "life-changing journeys",
  "uncharted territories",
  "shirt",
  "pants",
  "shoes",
  "socks",
  "jacket",
  "hat",
  "scarf",
  "gloves",
  "dress",
  "skirt",
  "tie",
  "coat",
  "sweater",
  "shorts",
  "rose",
  "daisy",
  "tulip",
  "oak",
  "maple",
  "pine",
  "willow",
  "birch",
  "cedar",
  "cypress",
  "poplar",
  "ash",
  "elm",
  "fir",
  "juniper",
  "larch",
  "mahogany",
  "chestnut",
  "hickory",
  "cedar",
  "walnut",
  "beech",
  "cherry",
  "apple",
  "peach",
  "pizza",
  "pasta",
  "burger",
  "sandwich",
  "sushi",
  "salad",
  "steak",
  "taco",
  "chicken",
  "rice",
  "noodles",
  "soup",
  "burrito",
  "quesadilla",
  "hotdog",
  "fries",
  "wings",
  "ribs",
  "lasagna",
  "meatloaf",
  "mac and cheese",
  "grilled cheese",
  "pancakes",
  "waffles",
  "omelette",
  "scrambled eggs",
  "bacon",
  "sausage",
  "hash browns",
  "muffins",
  "bagels",
  "donuts",
  "croissant",
  "toast",
  "cereal",
  "yogurt",
  "granola",
  "smoothie",
  "milkshake",
  "ice cream",
  "cake",
  "pie",
  "cookies",
  "brownies",
  "cupcakes",
  "pudding",
  "jelly",
  "candy",
  "chocolate",
  "chips",
  "pretzels",
  "popcorn",
  "nuts",
  "fruit",
  "vegetables",
  "popsicle",
  "cheese",
  "crackers",
  "bread",
  "hamburger",
  "bacon cheeseburger",
  "veggie burger",
  "fried chicken",
  "BBQ",
  "tuna sandwich",
  "reuben sandwich",
  "club sandwich",
  "shrimp",
  "lobster",
  "crab",
  "fish and chips",
  "clam chowder",
  "lobster bisque",
  "seafood paella",
  "mahi mahi",
  "salmon",
  "trout",
  "cod",
  "halibut",
  "tuna",
  "swordfish",
  "anchovies",
  "mackerel",
  "herring",
  "sardines",
  "oysters",
  "caviar",
  "lemon",
  "lime",
  "orange",
  "apple",
  "banana",
  "strawberries",
  "blueberries",
  "raspberries",
  "blackberries",
  "watermelon",
  "grapes",
  "peaches",
  "plums",
  "apricots",
  "cherries",
  "pears",
  "pineapple",
  "kiwi",
  "mango",
  "papaya",
  "coconut",
  "avocado",
  "piano",
  "guitar",
  "violin",
  "trumpet",
  "flute",
  "clarinet",
  "saxophone",
  "drums",
  "trombone",
  "cello",
  "harp",
  "ukulele",
  "accordion",
  "bass guitar",
  "bagpipes",
  "bongos",
  "kazoo",
  "harmonica",
  "maracas",
  "oboe",
  "piccolo",
  "tambourine",
  "xylophone",
  "organ",
  "triangle",
  "santoor",
  "vibraphone",
  "accordion",
  "electric guitar",
  "electric keyboard",
  "glockenspiel",
  "fiddle",
  "kalimba",
  "lyre",
];
var random_list_18 = [];
for (var i = 0; i < 18; i++) {
  random_list_18.push(random_nouns[Math.round(Math.random()*random_nouns.length)])
};

function setup() {
  createCanvas(625, 400);
}

function draw() {
  background(210,120,30);
  textSize(18);
  textAlign(LEFT,CENTER);
  for (var i = 0; i < 9; i++) {
    text('-' + str(random_list_18[i]), 0+width*0.025, i*400/9+400/18);
    text('-' + str(random_list_18[i+9]), width/2, i*400/9+400/18);
  };
}